import React, { useState, useEffect } from 'react';
import { X, Upload, Check, Camera, User, Phone, Mail, MapPin, ShieldCheck, Sparkles, MessageSquare, Coins, Calendar } from 'lucide-react';
import { CLASSES, CLASS_SUBJECTS, GENDERS } from '../../constants/academicData';
import { generateNextStudentId } from '../../utils/storage';

export default function AddStudentModal({ isOpen, onClose, onAddStudent, existingStudents }) {
  if (!isOpen) return null;

  const autoGeneratedId = generateNextStudentId(existingStudents);
  const todayStr = new Date().toISOString().split('T')[0];

  const [formData, setFormData] = useState({
    id: autoGeneratedId,
    firstName: '',
    lastName: '',
    pic: '',
    gender: '',
    contactNumber: '',
    whatsappNumber: '',
    email: '',
    address: '',
    fatherName: '',
    fatherContact: '',
    fatherCnic: '',
    studentClass: '',
    subject: '',
    fees: '',
    dateOfJoining: todayStr
  });

  const [errors, setErrors] = useState({});
  const [photoPreview, setPhotoPreview] = useState(null);

  // Reset all fields when opening dialog
  useEffect(() => {
    if (isOpen) {
      setFormData({
        id: generateNextStudentId(existingStudents),
        firstName: '',
        lastName: '',
        pic: '',
        gender: '',
        contactNumber: '',
        whatsappNumber: '',
        email: '',
        address: '',
        fatherName: '',
        fatherContact: '',
        fatherCnic: '',
        studentClass: '',
        subject: '',
        fees: '',
        dateOfJoining: todayStr
      });
      setPhotoPreview(null);
      setErrors({});
    }
  }, [isOpen]);

  // When class changes, do not auto-select subject; let user select it
  const handleClassChange = (newClass) => {
    setFormData(prev => ({
      ...prev,
      studentClass: newClass,
      subject: ''
    }));
  };

  const handleImageChange = (e) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        setPhotoPreview(reader.result);
        setFormData(prev => ({ ...prev, pic: reader.result }));
      };
      reader.readAsDataURL(file);
    }
  };

  // CNIC auto-formatter: XXXXX-XXXXXXX-X
  const handleCnicChange = (e) => {
    let val = e.target.value.replace(/\D/g, ''); // only digits
    if (val.length > 13) val = val.slice(0, 13);
    
    let formatted = val;
    if (val.length > 5 && val.length <= 12) {
      formatted = `${val.slice(0, 5)}-${val.slice(5)}`;
    } else if (val.length > 12) {
      formatted = `${val.slice(0, 5)}-${val.slice(5, 12)}-${val.slice(12, 13)}`;
    }

    setFormData(prev => ({ ...prev, fatherCnic: formatted }));
  };

  const validate = () => {
    const errs = {};
    if (!formData.firstName.trim()) errs.firstName = 'First name is required';
    if (!formData.lastName.trim()) errs.lastName = 'Last name is required';
    if (!formData.contactNumber.trim()) errs.contactNumber = 'Contact number is required';
    if (!formData.fatherName.trim()) errs.fatherName = 'Father / Guardian name is required';
    if (!formData.fatherContact.trim()) errs.fatherContact = 'Guardian contact is required';
    if (!formData.fatherCnic.trim()) {
      errs.fatherCnic = 'Guardian CNIC is required';
    } else if (formData.fatherCnic.length < 15) {
      errs.fatherCnic = 'CNIC format must be XXXXX-XXXXXXX-X';
    }
    if (!formData.gender) errs.gender = 'Gender is required';
    if (!formData.studentClass) errs.studentClass = 'Class is required';
    if (!formData.subject) errs.subject = 'Please select a section';
    if (!formData.fees) errs.fees = 'Monthly fees is required';

    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!validate()) return;

    // Use default placeholder if no pic was uploaded
    const finalPic = formData.pic || (
      formData.gender === 'Female'
        ? 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256'
        : 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=256'
    );

    const newStudent = {
      ...formData,
      pic: finalPic,
      registeredAt: new Date().toISOString().split('T')[0]
    };

    onAddStudent(newStudent);
    onClose();
  };

  const currentAvailableSubjects = CLASS_SUBJECTS[formData.studentClass] || [];

  return (
    <div className="fixed inset-0 z-50 bg-black/60 backdrop-blur-xs flex items-end sm:items-center justify-center p-0 sm:p-4 animate-in fade-in duration-200">
      <div 
        className="bg-white w-full max-w-md rounded-t-3xl sm:rounded-3xl max-h-[92vh] flex flex-col shadow-2xl overflow-hidden border border-slate-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between bg-gradient-to-r from-indigo-50 to-white">
          <div className="flex items-center gap-2">
            <div className="w-9 h-9 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-sm">
              <User className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-800">Add New Student</h2>
              <p className="text-xs text-slate-500">Enter student details & enrollment</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 flex items-center justify-center text-slate-500 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Form Body - Scrollable */}
        <form onSubmit={handleSubmit} className="overflow-y-auto px-5 py-4 space-y-4 text-xs">
          
          {/* Autogenerated Student ID Badge */}
          <div className="bg-indigo-50/80 border border-indigo-100 rounded-xl p-3 flex items-center justify-between">
            <div>
              <span className="text-[11px] font-semibold text-indigo-700 uppercase tracking-wider block">
                Student ID (Auto-Generated)
              </span>
              <span className="text-sm font-extrabold text-indigo-950 font-mono tracking-tight">
                {formData.id}
              </span>
            </div>
            <div className="flex items-center gap-1 bg-white px-2 py-1 rounded-md text-[10px] font-medium text-indigo-600 shadow-xs border border-indigo-100">
              <Sparkles className="w-3 h-3 text-amber-500" />
              Serial-wise
            </div>
          </div>

          {/* Picture Upload / Attachment Placeholder */}
          <div className="bg-slate-50 border border-dashed border-slate-300 rounded-2xl p-3.5 flex items-center gap-3.5">
            <div className="relative w-16 h-16 rounded-xl bg-white border-2 border-indigo-100 overflow-hidden flex items-center justify-center shadow-xs shrink-0">
              {photoPreview ? (
                <img src={photoPreview} alt="Preview" className="w-full h-full object-cover" />
              ) : (
                <User className="w-7 h-7 text-slate-300" />
              )}
              <div className="absolute inset-0 bg-black/10 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                <Camera className="w-4 h-4 text-white drop-shadow" />
              </div>
            </div>

            <div className="flex-1">
              <span className="block font-semibold text-slate-700 text-xs mb-1">
                Student Photo (Attachment Placeholder)
              </span>
              <p className="text-[11px] text-slate-400 mb-2">
                Upload student passport size photo or placeholder
              </p>
              <label className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-semibold cursor-pointer shadow-xs transition-colors">
                <Upload className="w-3.5 h-3.5" />
                <span>Upload Pic</span>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleImageChange}
                  className="hidden"
                />
              </label>
            </div>
          </div>

          {/* First Name & Last Name */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block font-semibold text-slate-700 mb-1">
                First Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                value={formData.firstName}
                onChange={(e) => setFormData({ ...formData, firstName: e.target.value })}
                placeholder="e.g. Bilal"
                className={`w-full px-3 py-2 rounded-xl border bg-white text-xs focus:outline-none focus:ring-2 ${
                  errors.firstName ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                }`}
              />
              {errors.firstName && <p className="text-rose-500 text-[10px] mt-0.5">{errors.firstName}</p>}
            </div>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">
                Last Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                value={formData.lastName}
                onChange={(e) => setFormData({ ...formData, lastName: e.target.value })}
                placeholder="e.g. Khan"
                className={`w-full px-3 py-2 rounded-xl border bg-white text-xs focus:outline-none focus:ring-2 ${
                  errors.lastName ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                }`}
              />
              {errors.lastName && <p className="text-rose-500 text-[10px] mt-0.5">{errors.lastName}</p>}
            </div>
          </div>

          {/* Gender (Radio Buttons / Segmented) */}
          <div>
            <label className="block font-semibold text-slate-700 mb-1.5">
              Gender <span className="text-rose-500">*</span>
            </label>
            <div className="grid grid-cols-3 gap-2">
              {GENDERS.map((gender) => (
                <label
                  key={gender}
                  className={`flex items-center justify-center gap-1.5 py-2 px-2.5 rounded-xl border cursor-pointer font-semibold text-xs transition-all ${
                    formData.gender === gender
                      ? 'bg-indigo-600 text-white border-indigo-600 shadow-xs'
                      : 'bg-white text-slate-600 border-slate-200 hover:bg-slate-50'
                  }`}
                >
                  <input
                    type="radio"
                    name="gender"
                    value={gender}
                    checked={formData.gender === gender}
                    onChange={() => setFormData({ ...formData, gender })}
                    className="sr-only"
                  />
                  <span>{gender}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Contact Number & WhatsApp Number */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block font-semibold text-slate-700 mb-1">
                Contact Number <span className="text-rose-500">*</span>
              </label>
              <div className="relative">
                <input
                  type="tel"
                  value={formData.contactNumber}
                  onChange={(e) => setFormData({ ...formData, contactNumber: e.target.value })}
                  placeholder="0300-1234567"
                  className={`w-full pl-7 pr-3 py-2 rounded-xl border bg-white text-xs focus:outline-none focus:ring-2 ${
                    errors.contactNumber ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                  }`}
                />
                <Phone className="w-3.5 h-3.5 text-slate-400 absolute left-2 top-2.5" />
              </div>
              {errors.contactNumber && <p className="text-rose-500 text-[10px] mt-0.5">{errors.contactNumber}</p>}
            </div>

            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="block font-semibold text-slate-700">
                  WhatsApp Number
                </label>
                {formData.contactNumber && (
                  <button
                    type="button"
                    onClick={() => setFormData({ ...formData, whatsappNumber: formData.contactNumber })}
                    className="text-[9px] text-emerald-600 hover:text-emerald-700 font-bold"
                  >
                    Same as contact
                  </button>
                )}
              </div>
              <div className="relative">
                <input
                  type="tel"
                  value={formData.whatsappNumber}
                  onChange={(e) => setFormData({ ...formData, whatsappNumber: e.target.value })}
                  placeholder="0300-1234567"
                  className="w-full pl-7 pr-3 py-2 rounded-xl border border-slate-200 bg-white text-xs focus:outline-none focus:ring-2 focus:ring-emerald-200 focus:border-emerald-500"
                />
                <MessageSquare className="w-3.5 h-3.5 text-emerald-500 absolute left-2 top-2.5" />
              </div>
            </div>
          </div>

          {/* Email */}
          <div>
            <label className="block font-semibold text-slate-700 mb-1">
              Email Address
            </label>
            <div className="relative">
              <input
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                placeholder="name@email.com"
                className="w-full pl-7 pr-3 py-2 rounded-xl border border-slate-200 bg-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500"
              />
              <Mail className="w-3.5 h-3.5 text-slate-400 absolute left-2 top-2.5" />
            </div>
          </div>

          {/* Address */}
          <div>
            <label className="block font-semibold text-slate-700 mb-1">
              Address
            </label>
            <div className="relative">
              <input
                type="text"
                value={formData.address}
                onChange={(e) => setFormData({ ...formData, address: e.target.value })}
                placeholder="House #, Street, City / Area"
                className="w-full pl-7 pr-3 py-2 rounded-xl border border-slate-200 bg-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500"
              />
              <MapPin className="w-3.5 h-3.5 text-slate-400 absolute left-2 top-2.5" />
            </div>
          </div>

          {/* Father / Guardian Section Divider */}
          <div className="pt-2 border-t border-slate-100">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider flex items-center gap-1.5 mb-2.5">
              <ShieldCheck className="w-3.5 h-3.5 text-indigo-600" />
              Father / Guardian Details
            </span>

            <div className="space-y-3">
              <div>
                <label className="block font-semibold text-slate-700 mb-1">
                  Father / Guardian Name <span className="text-rose-500">*</span>
                </label>
                <input
                  type="text"
                  value={formData.fatherName}
                  onChange={(e) => setFormData({ ...formData, fatherName: e.target.value })}
                  placeholder="Father's full name"
                  className={`w-full px-3 py-2 rounded-xl border bg-white text-xs focus:outline-none focus:ring-2 ${
                    errors.fatherName ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                  }`}
                />
                {errors.fatherName && <p className="text-rose-500 text-[10px] mt-0.5">{errors.fatherName}</p>}
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block font-semibold text-slate-700 mb-1">
                    Guardian Contact <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="tel"
                    value={formData.fatherContact}
                    onChange={(e) => setFormData({ ...formData, fatherContact: e.target.value })}
                    placeholder="0321-9876543"
                    className={`w-full px-3 py-2 rounded-xl border bg-white text-xs focus:outline-none focus:ring-2 ${
                      errors.fatherContact ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                    }`}
                  />
                  {errors.fatherContact && <p className="text-rose-500 text-[10px] mt-0.5">{errors.fatherContact}</p>}
                </div>

                <div>
                  <label className="block font-semibold text-slate-700 mb-1">
                    Guardian CNIC No <span className="text-rose-500">*</span>
                  </label>
                  <input
                    type="text"
                    value={formData.fatherCnic}
                    onChange={handleCnicChange}
                    maxLength={15}
                    placeholder="35202-1234567-1"
                    className={`w-full px-3 py-2 rounded-xl border bg-white text-xs font-mono focus:outline-none focus:ring-2 ${
                      errors.fatherCnic ? 'border-rose-400 focus:ring-rose-200' : 'border-slate-200 focus:ring-indigo-200 focus:border-indigo-500'
                    }`}
                  />
                  {errors.fatherCnic && <p className="text-rose-500 text-[10px] mt-0.5">{errors.fatherCnic}</p>}
                </div>
              </div>
            </div>
          </div>

          {/* Academic Enrollment Section */}
          <div className="pt-2 border-t border-slate-100">
            {/* Class Radio Buttons */}
            <div className="mb-3">
              <div className="flex items-center justify-between mb-1.5">
                <label className="font-bold text-slate-800 text-xs">
                  Class <span className="text-rose-500">*</span>
                </label>
                <span className="text-[10px] font-medium text-slate-400">Select one class</span>
              </div>
              <div className="grid grid-cols-2 gap-2">
                {CLASSES.map((cls) => {
                  const isSelected = formData.studentClass === cls;
                  return (
                    <label
                      key={cls}
                      className={`flex items-center gap-2 px-3 py-2.5 rounded-xl border cursor-pointer transition-all ${
                        isSelected
                          ? 'border-indigo-600 bg-indigo-50/90 text-indigo-900 shadow-xs'
                          : 'border-slate-200 bg-white text-slate-700 hover:border-slate-300'
                      }`}
                    >
                      <input
                        type="radio"
                        name="studentClass"
                        value={cls}
                        checked={isSelected}
                        onChange={() => handleClassChange(cls)}
                        className="w-3.5 h-3.5 text-indigo-600 focus:ring-indigo-500 border-slate-300"
                      />
                      <span className="font-bold text-xs">{cls}</span>
                    </label>
                  );
                })}
              </div>
            </div>

            {/* Dynamic Section Radio Buttons */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label className="font-bold text-slate-800 text-xs">
                  Section for <span className="text-indigo-600">{formData.studentClass}</span> <span className="text-rose-500">*</span>
                </label>
                <span className="text-[10px] font-medium text-slate-400">Radio button (Select 1)</span>
              </div>

              <div className="grid grid-cols-2 gap-2">
                {currentAvailableSubjects.map((sub) => {
                  const isSelected = formData.subject === sub;
                  return (
                    <label
                      key={sub}
                      className={`flex items-center gap-2 px-3 py-2.5 rounded-xl border cursor-pointer transition-all ${
                        isSelected
                          ? 'border-emerald-600 bg-emerald-50/80 text-emerald-950 shadow-xs'
                          : 'border-slate-200 bg-white text-slate-700 hover:border-slate-300'
                      }`}
                    >
                      <input
                        type="radio"
                        name="subject"
                        value={sub}
                        checked={isSelected}
                        onChange={() => setFormData({ ...formData, subject: sub })}
                        className="w-3.5 h-3.5 text-emerald-600 focus:ring-emerald-500 border-slate-300"
                      />
                      <span className="font-semibold text-xs leading-tight">{sub}</span>
                    </label>
                  );
                })}
              </div>
              {errors.subject && <p className="text-rose-500 text-[10px] mt-1">{errors.subject}</p>}
            </div>
          </div>

          {/* Fees & Date of Joining */}
          <div className="pt-2 border-t border-slate-100 space-y-2">
            <span className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
              Fees & Admission
            </span>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block font-semibold text-slate-700 mb-1">
                  Monthly Fees (PKR) <span className="text-rose-500">*</span>
                </label>
                <div className="relative">
                  <input
                    type="number"
                    value={formData.fees}
                    onChange={(e) => setFormData({ ...formData, fees: e.target.value })}
                    placeholder="e.g. 6500"
                    className="w-full pl-7 pr-3 py-2 rounded-xl border border-slate-200 bg-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 font-semibold"
                  />
                  <Coins className="w-3.5 h-3.5 text-amber-500 absolute left-2 top-2.5" />
                </div>
              </div>

              <div>
                <label className="block font-semibold text-slate-700 mb-1">
                  Date of Joining <span className="text-rose-500">*</span>
                </label>
                <div className="relative">
                  <input
                    type="date"
                    value={formData.dateOfJoining}
                    onChange={(e) => setFormData({ ...formData, dateOfJoining: e.target.value })}
                    className="w-full pl-7 pr-2 py-2 rounded-xl border border-slate-200 bg-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-200 focus:border-indigo-500 font-semibold text-slate-700"
                  />
                  <Calendar className="w-3.5 h-3.5 text-indigo-500 absolute left-2 top-2.5" />
                </div>
              </div>
            </div>
          </div>

          {/* Sticky Submit / Action Bar */}
          <div className="pt-3 border-t border-slate-100 flex items-center gap-2.5">
            <button
              type="button"
              onClick={onClose}
              className="flex-1 py-2.5 px-4 rounded-xl border border-slate-200 text-slate-600 font-semibold text-xs hover:bg-slate-50 transition-colors tap-active"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="flex-1 py-2.5 px-4 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs shadow-md shadow-indigo-200 flex items-center justify-center gap-1.5 transition-all tap-active"
            >
              <Check className="w-4 h-4" />
              Save Student
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
